#!/usr/bin/env node
/**
 * install.js — Vellum Agent Skill v1.2.0
 * Runs via postinstall + SKILL.md postInstall hook.
 */

import { spawnSync } from 'child_process';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';
import os from 'os';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BIN_JS = path.join(__dirname, 'bin.js');
const CLI_JS = path.join(__dirname, 'cli.js');

const isTermux = process.env.PREFIX?.includes('com.termux') ||
                 fs.existsSync('/data/data/com.termux');
const isRoot   = process.getuid?.() === 0;

function log(msg)  { console.log(`  vellum: ${msg}`); }
function warn(msg) { console.warn(`  vellum ⚠️  ${msg}`); }

// ── STEP 1: Fix ALL js file permissions immediately ───────────────────────────
function fixPermissions() {
  const executableFiles = [BIN_JS, CLI_JS, path.join(__dirname, 'install.js')];
  for (const f of executableFiles) {
    try {
      if (fs.existsSync(f)) {
        fs.chmodSync(f, 0o755);
        log(`chmod 755 → ${path.basename(f)} ✅`);
      }
    } catch (e) {
      // Try via shell
      try { spawnSync('chmod', ['755', f], { timeout: 3000 }); } catch {}
    }
  }
}

// ── STEP 2: Fix any existing symlinks that point to our files ─────────────────
function fixExistingInstalls() {
  const getNpmPrefix = () => {
    try {
      return spawnSync('npm', ['prefix', '-g'],
        { encoding: 'utf8', timeout: 8000 }).stdout?.trim();
    } catch { return null; }
  };

  const prefix = getNpmPrefix();
  const searchDirs = [
    prefix && path.join(prefix, 'bin'),
    '/usr/local/bin',
    '/usr/bin',
    process.env.PREFIX && path.join(process.env.PREFIX, 'bin'),
  ].filter(Boolean);

  for (const dir of searchDirs) {
    const vellumPath = path.join(dir, 'vellum');
    try {
      const stat = fs.lstatSync(vellumPath);
      if (stat.isSymbolicLink()) {
        // Fix permission on the symlink target
        const target = fs.realpathSync(vellumPath);
        try { fs.chmodSync(target, 0o755); } catch {}
        log(`Fixed symlink target: ${vellumPath} → ${target} ✅`);
      } else if (stat.isFile()) {
        try { fs.chmodSync(vellumPath, 0o755); } catch {}
        log(`Fixed wrapper: ${vellumPath} ✅`);
      }
    } catch {}
  }
}

// ── STEP 3: Install global command ───────────────────────────────────────────
function getNpmPrefix() {
  try {
    return spawnSync('npm', ['prefix', '-g'],
      { encoding: 'utf8', timeout: 8000 }).stdout?.trim() || null;
  } catch { return null; }
}

function writeWrapperScript(destDir, name = 'vellum') {
  try {
    fs.mkdirSync(destDir, { recursive: true });
    const wrapperPath = path.join(destDir, name);

    // Write a /bin/sh wrapper — this NEVER needs chmod on the target
    // because sh -c or `node file` don't require execute bit on the file itself
    const wrapper = [
      '#!/bin/sh',
      '# Vellum Agent Skill wrapper — auto-generated by install.js',
      `exec node "${BIN_JS}" "$@"`,
    ].join('\n') + '\n';

    fs.writeFileSync(wrapperPath, wrapper);

    // chmod the wrapper itself to 755
    try { fs.chmodSync(wrapperPath, 0o755); } catch {
      try { spawnSync('chmod', ['755', wrapperPath], { timeout: 3000 }); } catch {}
    }

    log(`Shell wrapper → ${wrapperPath} ✅`);
    return true;
  } catch (e) {
    warn(`Wrapper at ${destDir}: ${e.message}`);
    return false;
  }
}

function addShellAlias() {
  // `node bin.js` never needs execute bit — node reads the file, not executes it
  const aliasLine = `alias vellum='node "${BIN_JS}"'`;
  const shells = [
    path.join(os.homedir(), '.bashrc'),
    path.join(os.homedir(), '.zshrc'),
    path.join(os.homedir(), '.profile'),
    path.join(os.homedir(), '.bash_profile'),
    process.env.PREFIX && path.join(process.env.PREFIX, 'etc', 'bash.bashrc'),
  ].filter(Boolean);

  for (const sh of shells) {
    try {
      const existing = fs.existsSync(sh) ? fs.readFileSync(sh, 'utf8') : '';
      if (!existing.includes('alias vellum=')) {
        fs.appendFileSync(sh, `\n# Vellum Agent Skill\n${aliasLine}\n`);
        log(`Alias added → ${sh}`);
        return sh;
      } else {
        // Update existing alias to point to new location
        const updated = existing.replace(
          /alias vellum=.*/g,
          aliasLine
        );
        fs.writeFileSync(sh, updated);
        log(`Alias updated → ${sh}`);
        return sh;
      }
    } catch {}
  }
  return null;
}

function installGlobal() {
  log('Installing global vellum command...');

  // Try 1: npm link
  try {
    const r = spawnSync('npm', ['link', '--ignore-scripts'], {
      cwd: __dirname, encoding: 'utf8', timeout: 60000, stdio: 'pipe',
    });
    if (r.status === 0) { log('npm link ✅'); return 'npm-link'; }
    warn(`npm link: ${r.stderr?.trim()?.slice(0, 100)}`);
  } catch (e) { warn(`npm link: ${e.message}`); }

  // Try 2: Write shell wrapper to npm global bin
  const prefix = getNpmPrefix();
  if (prefix) {
    if (writeWrapperScript(path.join(prefix, 'bin'))) return 'wrapper-npm';
  }

  // Try 3: System bin dirs
  for (const dir of ['/usr/local/bin', '/usr/bin']) {
    if (fs.existsSync(dir)) {
      if (writeWrapperScript(dir)) return 'wrapper-sys';
    }
  }

  // Try 4: Shell alias (always works, no permissions needed)
  const aliasFile = addShellAlias();
  if (aliasFile) return `alias:${aliasFile}`;

  return null;
}

// ── STEP 4: Protect read-only files (NEVER include bin.js or cli.js!) ────────
function protectReadonlyFiles() {
  // IMPORTANT: cli.js and bin.js must stay 755 (executable)
  // Only protect documentation/config files with 444
  const readOnly = ['SKILL.md', 'package.json', 'README.md', '.gitattributes'];
  for (const f of readOnly) {
    const fp = path.join(__dirname, f);
    try { if (fs.existsSync(fp)) fs.chmodSync(fp, 0o444); } catch {}
  }
  // install.js itself: keep readable but lock it
  try { fs.chmodSync(path.join(__dirname, 'install.js'), 0o444); } catch {}
}

// ── MAIN ──────────────────────────────────────────────────────────────────────
console.log('\n  ┌─ Vellum Agent Skill Setup ──────────────────┐');
console.log(`  │  v1.2.0  ${os.platform()}  ${isTermux ? '[Termux]' : isRoot ? '[root]' : '[user]'}`);
console.log(`  │  Node ${process.version}`);
console.log('  └─────────────────────────────────────────────┘\n');

// Always fix permissions first — even if already installed
fixPermissions();
fixExistingInstalls();

// Check if vellum already works
const test = spawnSync('vellum', ['--version'], { encoding: 'utf8', timeout: 3000 });
if (test.status === 0) {
  log('vellum already working globally ✅');
} else {
  const result = installGlobal();
  if (!result) {
    console.log('\n  ── Manual setup ─────────────────────────────');
    console.log(`  node "${BIN_JS}" --help`);
    console.log(`  echo "alias vellum='node \\"${BIN_JS}\\"'" >> ~/.bashrc`);
    console.log('  source ~/.bashrc');
    console.log('  ─────────────────────────────────────────────\n');
  } else if (result.startsWith('alias:')) {
    const f = result.split(':')[1];
    console.log('\n  ✅ Installed via shell alias');
    console.log(`  Activate: source ${f}`);
    console.log('  Then run: vellum --help\n');
  }
}

// Protect files LAST — and NEVER touch bin.js or cli.js with 444
protectReadonlyFiles();
// Re-ensure executables stay at 755 after protectReadonlyFiles
try { fs.chmodSync(BIN_JS, 0o755); } catch {}
try { fs.chmodSync(CLI_JS, 0o755); } catch {}

console.log('');
